const SET_STREAM_STATUS = 'SET_STREAM_STATUS';
const GET_STREAM_STATUS = 'GET_STREAM_STATUS';
const SET_STREAM_PROFILE = 'SET_STREAM_PROFILE';
const GET_STREAM_PROFILE = 'GET_STREAM_PROFILE';

export {
  SET_STREAM_STATUS,
  GET_STREAM_STATUS,
  SET_STREAM_PROFILE,
  GET_STREAM_PROFILE,
};
