const SET_SC_ORGANISATION = 'SET_SC_ORGANISATION';
const GET_SC_ORGANISATION = 'GET_SC_ORGANISATION';
const SET_SC_PERSON = 'SET_SC_PERSON';
const GET_SC_PERSON = 'GET_SC_PERSON';

export {
  SET_SC_ORGANISATION,
  GET_SC_ORGANISATION,
  SET_SC_PERSON,
  GET_SC_PERSON
};
